### ISSUE TITLE
Referring to lazy child component

### ISSUE THREAD

**Issue by haggholm** [iammerrick/how-to-lazy-load-react-webpack#3]
I feel I must be missing something that ought to be obvious, but…well, maybe you can save me some time and torn-out hair. I have some code that needs to call *methods* on the lazily loaded component:

```javascript
class SomeComponent extends React.Component {
  render() {
    return (
      <LazilyLoad ref="foo" modules={/*...*/}>
        { /* ... */ }
      </LazilyLoad>
    );
  }

  someFunc() {
    this.refs.foo.bar();
  }
}
```

Obviously this can only work on async methods, but it seems that it should be feasible, and ideally without  the parent(s) having to be aware whether some child component happens to be loaded lazily or not.

**Comment by iammerrick** [comment]
Hey Haggholm! Yeah! I got you. I pushed a new commit that includes an example:

https://github.com/iammerrick/how-to-lazy-load-react-webpack/commit/0336257f6b50984cd2df44cce5e55a123ef6df3d

If you can avoid refs I recommend it! But if you can't thats ok, you can still use ref callbacks!

// P.S. I think your main gotcha here is that you are adding ref to LazilyLoad instead of your components themselves.
